# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'iPromise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iPromise
pod 'R.swift'
pod 'JNPhoneNumberView'
pod 'AdvancedPageControl'
pod 'MaterialComponents/TextControls+OutlinedTextFields'
pod 'DropDown'
pod 'GrowingTextView', '0.7.2'
end
